### PR TITLE
CI for windows

### LINKED ISSUE #1131: CI: Add a way to test on windows
Add a way to test the workshop on windows

### PR DESCRIPTION
**Pull request by barelyhuman**
Closes #1131

### CODE REVIEW

**Review by simoneb — CHANGES_REQUESTED** [review]
no need to have a dedicated workflow. see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#using-a-github-hosted-runner

**Comment by simoneb** [comment]
oh ok I see that and I wasn't aware that containers were not supported. if that is the case, we can do without windows support then

**Comment by barelyhuman** [comment]
thoughts on forking the action being used vs helping the author maintain it?

**Comment by simoneb** [comment]
why would we need to fork the action?

**Review by simoneb — APPROVED** [review]

**Pull request merged**
