### PR TITLE
Update .env

### LINKED ISSUE #905: Database section localhost -> 0.0.0.0
On page 74 the following postgres address is suggested 
`PG_CONNECTION_STRING=postgres://postgres:postgres@localhost:5433/postgres`
This didn't work for me, and resulted in the following error message:
```
req: {
      "method": "POST",
      "url": "/login",
      "hostname": "localhost:3000",
      ...
    }
    res: {
      "statusCode": 500
    }
    err: {
      "type": "Error",
      "message": "connect ECONNREFUSED ::1:5433",
      "stack":
          Error: connect ECONNREFUSED ::1:5433
              at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
      "errno": -61,
      "code": "ECONNREFUSED",
      "syscall": "connect",
      "address": "::1",
      "port": 5433
    }
 ...
```
As you can see the address points to `::1`. After discussing this with @SociableSteve it appears to be that using `localhost` doesn't work in `PG_CONNECTION_STRING`. Replacing it with `0.0.0.0` resolved the issue, and would recommend this change, however, my understanding of it is limited, and so if there is a better way, please let me know.

### PR DESCRIPTION
**Pull request by Ademsk1**
fixes #905

### CODE REVIEW

**Comment by Ademsk1** [comment]
@simoneb seems to have worked. I'm assuming using 0.0.0.0 doesn't have any security vulnerabilities on the Github servers, but I guess there's no sensitive data, so I'm sure it's not an issue.

**Review by simoneb — COMMENTED** [review]
LGTM, are there any other occurrences of this string throughout the repo?

**Comment by Ademsk1** [comment]
> LGTM, are there any other occurrences of this string throughout the repo?

Yup, in the slides, I'll patch those up

**Review by simoneb — APPROVED** [review]

**Comment by simoneb** [comment]
@Ademsk1 when you address PR feedback remember to re-request a review, otherwise reviewers won't know you've pushed more changes

**Comment by Ademsk1** [comment]
> @Ademsk1 when you address PR feedback remember to re-request a review, otherwise reviewers won't know you've pushed more changes

Yes! Apologies!

**Pull request merged**
